# Generated by Django 4.1.7 on 2023-03-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipies',
            },
        ),
    ]
