# Generated by Django 4.1.7 on 2023-04-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='img',
            new_name='image',
        ),
    ]
