# Generated by Django 4.1.7 on 2023-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipe_rec_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
